# Generated by the local bootstrap-gha-cicd module.
# While changes won't be overwritten unless run locally and committed, highly recommended
# to not change this outside of the module.
provider "github" {
  owner = "qop-maintainer"
}
