# Generated by the local bootstrap-aws-account module.
# While changes won't be overwritten unless run locally and committed, highly recommended
# to not change this outside of the module.
terraform {
  backend "s3" {
    bucket        = "qop-maintainer-terraform-state-eu-west-2"
    key           = "terraform-state"
    region        = "eu-west-2"
    encrypt       = true
    kms_key_id    = "alias/aws/s3"
    use_lockfile  = true
  }
}
