# Generated by the local bootstrap-aws-account module.
# While changes won't be overwritten unless run locally and committed, highly recommended
# to not change this outside of the module.
terraform {
  required_version = "1.14.6"

  required_providers {
    github = {
      source  = "integrations/github"
      version = "6.11.1"
    }
    aws = {
      source  = "hashicorp/aws"
      version = "6.34.0"
    }
    local = {
      source  = "hashicorp/local"
      version = "2.7.0"
    }
  }
}
