name: Continuous Integration

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/continuous-integration.yml'
      - 'terraform/**'
      - 'mise.toml'

  push:
    branches:
      - main
    paths:
      - '.github/workflows/continuous-integration.yml'
      - 'terraform/**'
      - 'mise.toml'

permissions: {}

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          disable-sudo-and-containers: true
          egress-policy: audit
          allowed-endpoints: >
            github.com:443

      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Perform Review
        uses: actions/dependency-review-action@2031cfc080254a8a887f58cffee85186f0e49e48 # v4.9.0

  terraform:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    env:
      TF_IN_AUTOMATION: true
      WORKING_DIRECTORY: terraform

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          disable-sudo: true
          egress-policy: audit
          allowed-endpoints: >
            github.com:443
            registry.terraform.io:443

      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          show-progress: false

      - name: Retrieve Terraform version from mise.toml
        id: terraform-version
        run: echo "version=$(yq .tools.terraform mise.toml)" >> "$GITHUB_OUTPUT"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
        with:
          terraform_version: ${{ steps.terraform-version.outputs.version }}

      - name: Configure AWS credentials PR (read-only)
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_PLAN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Initialise
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: terraform init -input=false -no-color
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Prettify
        run: terraform fmt -check -no-color
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Validate
        run: terraform validate -no-color
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Plan
        run: terraform plan -input=false -no-color
        working-directory: ${{ env.WORKING_DIRECTORY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
